#!/bin/bash

PREV_COMMIT=$1
POST_COMMIT=$2

echo $PREV_COMMIT

NOCOLOR='\e[0m'
REDCOLOR='\e[37;41m'

if [[ -f composer.lock ]]; then
    if [ "$PREV_COMMIT" -eq 0 ]; then
      DIFF=yes
    else
      DIFF=`git diff --shortstat $PREV_COMMIT..$POST_COMMIT composer.lock`
    fi
    if [[ $DIFF != "" ]]; then
        echo -e "$REDCOLOR composer.lock has changed. You must run composer install$NOCOLOR"
    fi
fi
